version: "3.8"
services:
  web:
    build: 
      context: ./my-app
      target: development
    ports:
      - "5001:5001"
    volumes:
      - ./my-app:/app
    links:
      - db:postgres
    container_name: app_web_1
    depends_on:
      - db
    environment:
      PORT: 5001
      SECRET_KEY: "you-will-never-guess"
      ENV_FOR_DYNACONF: development
      DB_USERNAME: app_user
      DB_PASSWORD: app_password
      DB_HOST: postgres
      DATABASE_NAME: app

  db:
    image: postgres:14-alpine
    restart: always
    container_name: app_db_1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
      POSTGRES_DB: app


