[default]
SECRET_KEY = "you-will-never-guess"
DB_USERNAME = "app_user"
DB_PASSWORD = "app_password"
DATABASE_NAME = "app"

[development]
DB_HOST = "localhost"

[docker]
DB_HOST = "db"

[testing]
TESTING = true
DB_HOST = "testing-db"

[staging]
DB_HOST = "staging-db"

[production]
DB_HOST = "production-db"
